export const ERROR_CODES = {
    UNAUTHORIZED: "UNAUTHORIZED",
    FORBIDDEN: "FORBIDDEN",
    VALIDATION_ERROR: "VALIDATION_ERROR",
    BOOK_NOT_FOUND: "BOOK_NOT_FOUND",
    BOOK_NOT_AVAILABLE: "BOOK_NOT_AVAILABLE",
    DUPLICATE_ISBN: "DUPLICATE_ISBN",
    LOAN_NOT_FOUND: "LOAN_NOT_FOUND",
    MAX_BORROW_LIMIT_REACHED: "MAX_BORROW_LIMIT_REACHED",
    ACCOUNT_SUSPENDED: "ACCOUNT_SUSPENDED",
    CONFLICT: "CONFLICT",
    INTERNAL_SERVER_ERROR: "INTERNAL_SERVER_ERROR"
} as const;
